// layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Varela_Round } from 'next/font/google';

const varela = Varela_Round({
    subsets: ['latin'],
    weight: ['400'], // Varela Round chỉ có 400 weight
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`antialiased ${varela.className}`}>{children}</body>
            </html>
        </ClerkProvider>
    );
}
